# SPDX-FileCopyrightText: Copyright 2025 The SLSA Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Go Tests (sourcetool)

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Extract version of Go to use
        run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.GOVERSION }}
          check-latest: true
          cache: false

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0

      - name: Setup protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # @v3.0.0

      - name: Run Go tests
        run: |
          go test -v ./...

      - name: Check generated fakes
        run: |
          hack/verify-fakes.sh

      - name: Check protobuf generated codew
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          hack/verify-protos.sh
